### ISSUE TITLE
The project does not support adding package references through the add package command.

### ISSUE THREAD

**Issue by ghost** [obfuscar/example#1]
Hi, when i try to add package to my protect using command `dotnet add package Obfuscar --version 2.2.11` it says  "The project does not support adding package references through the add package command." but msdn do not tell about this error so how do i do?

Actual output:
```
Writing C:\Users\username\AppData\Local\Temp\tmp17C4.tmp
info : Adding PackageReference for package 'Obfuscar' into project '[path censored]\My project.csproj'.
error: Error while adding package 'Obfuscar' to project '[path censored]\My project.csproj'. The project does not support adding package references through the add package command.
```

**Comment by lextm** [comment]
I cannot reproduce it.

What is the output of `dotnet --version` on your machine?

**Comment by ghost** [comment]
My version is 2.1.2

**Comment by ghost** [comment]
I tried Package Installer but got errors

```
PS [censored path]> Install-Package Obfuscar -Version 2.2.11
Install-Package : A parameter cannot be found that matches parameter name 'Version'.
At line:1 char:26
+ Install-Package Obfuscar -Version 2.2.11
+                          ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS [censored path]> Install-Package Obfuscar
Install-Package : No match was found for the specified search criteria and package name 'Obfuscar'. Try Get-PackageSour
ce to see all available registered package sources.
At line:1 char:1
+ Install-Package Obfuscar
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Problem for me is your documentation is suck and unclear so i tried to do things by myself with no luck

**Comment by lextm** [comment]
Cannot reproduce that either.

You probably should review your machine to dig further, such as Visual Studio version, NuGet Package Manager version.

**Comment by ghost** [comment]
Well nvm, i found other way to install the package via Visual Studio. Now how do i get started setting up obfuscator? can i have clear documentation about it?

**Comment by lextm** [comment]
http://docs.obfuscar.com/en/latest/

**Comment by bunmalik** [comment]
Please I got the same error:
I am using ubuntu 16.04, dotnet version is 2.1.400.
When I typed this in the terminal, 
$ dotnet add package System.Threading.Tasks.Dataflow --version 4.9.0

Writing /tmp/tmpNmBeM9.tmp
info : Adding PackageReference for package 'System.Threading.Tasks.Dataflow' into project '/home/bunmalik/Desktop/thesis/codes/cs/PALNS-master (2)/Palns/Palns.csproj'.
error: Error while adding package 'System.Threading.Tasks.Dataflow' to project '/home/bunmalik/Desktop/thesis/codes/cs/PALNS-master (2)/Palns/Palns.csproj'. The project does not support adding package references through the add package command.

i got this error...
Please I need help on this, I am new to csharp!

**Comment by chrisp196** [comment]
I also got this error.
My dotnet version is 2.1.400.
dotnet add package RestSharp --version 106.3.1 

Writing D:\local\Temp\tmpB520.tmp
info : Adding PackageReference for package 'RestSharp' into project 'D:\home\site\wwwroot\Microsoft.Bot.Sample.LuisBot.csproj'.
error: Error while adding package 'RestSharp' to project 'D:\home\site\wwwroot\Microsoft.Bot.Sample.LuisBot.csproj'. The project does not support adding package references through the add package command.

**Comment by federico22285** [comment]
I got as well the same error ...  version 2.1.401

**Comment by ahadGitHub** [comment]
install-package "package name" 
is a work around.

**Comment by v-kravets** [comment]
Found this is reproducible using dotnet version 6.0.100 for the project that is .Net Framework v.4.8. When this project is in the state without any package references and you try to add some using dotnet command from command line - it fails with "The project does not support adding package references through the add package command." error. For .Net Standard project command works as expected.

**Comment by sitting-duck** [comment]
> Found this is reproducible using dotnet version 6.0.100 for the project that is .Net Framework v.4.8. When this project is in the state without any package references and you try to add some using dotnet command from command line - it fails with "The project does not support adding package references through the add package command." error. For .Net Standard project command works as expected.

Can confirm, was able to reproduce this on Windows 11, VStudio 2019, .NET Target Framework in the .csproj file was 4.7.2,
searched for TargetFrameworkVersion node in the .csproj file to detect this, 
```
<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
```
and 
```
> dotnet --version
6.0.201
```
reveals I am using .NET 6. 

Hopefully this will help others check for this condition as well.

**Comment by nhat3eo22** [comment]
In Visual Studio, in your project, in References->Manage NuGet Packages->Update your package that make error, and your package will add to references

**Comment by eaengler** [comment]
I had the same error when using 'await' within an async function when calling an IAsyncOperation method. It was saying my method did not have a definition for 'GetAwaiter'. Could not install the package via the command line dotnet messsage. This fixed all my errors:  I went to References > Manage NuGet Packages > Browse "System.Runtime.WindowsRuntime" and make sure it is installed.

![image](https://user-images.githubusercontent.com/111146212/226792726-20583e10-a3de-4f7e-942d-81a1643ec14a.png)

**Comment by rawhide81** [comment]
I've got a similar Error Message ...

PS C:\Users\rbb\source\repos> dotnet add RelaventLegalMatters package NuGet

Build succeeded in 0.2s
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'NuGet' into project 'C:\Users\rbb\source\repos\RelaventLegalMatters\RelaventLegalMatters.csproj'.
error: Error while adding package 'NuGet' to project 'C:\Users\rbb\source\repos\RelaventLegalMatters\RelaventLegalMatters.csproj'. The project does not support adding package references through the add package command.

Could someone possibly steer me to some relevant docs, or hints???

**Comment by rawhide81** [comment]
PS

I have verified dotnet --version 9 and tried Install-Package with these results ...

PS C:\Users\rbb\source\repos> Install-Package Microsoft.EntityFrameworkCore.SqlServer
Install-Package : No match was found for the specified search criteria and package name
'Microsoft.EntityFrameworkCore.SqlServer'. Try Get-PackageSource to see all available registered package sources.
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.SqlServer
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by rawhide81** [comment]
Now I have this lol ... I just need to know if it's a case of RTFM. then I'll do the rest????

PS C:\Users\rbb\source\repos> dotnet add RelaventLegalMatters package Microsoft.EntityFrameworkCore.sqlServer
  Determining projects to restore...
  Writing C:\Users\rbb\AppData\Local\Temp\tmpfjnp21.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.sqlServer' into project 'C:\Users\rbb\source\repos\RelaventLegalMa
tters\RelaventLegalMatters.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/index.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/index.json 250ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/page/0.0.1-alpha/3.1.2.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/page/0.0.1-alpha/3.1.2.json 248ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/page/3.1.3/6.0.0-preview.6.21352.1.js
on
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/page/3.1.3/6.0.0-preview.6.21352.1.jso
n 250ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/page/6.0.0-preview.7.21378.4/7.0.17.j
son
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/page/6.0.0-preview.7.21378.4/7.0.17.js
on 252ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/page/7.0.18/10.0.0-preview.1.25081.1.
json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.entityframeworkcore.sqlserver/page/7.0.18/10.0.0-preview.1.25081.1.j
son 247ms
info : Restoring packages for C:\Users\rbb\source\repos\RelaventLegalMatters\RelaventLegalMatters.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 253ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/9.0.2/microsoft.entityframeworkcore.sqlserver.9.
0.2.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/9.0.2/microsoft.entityframeworkcore.sqlserver.9.0
.2.nupkg 104ms
info : Installed Microsoft.EntityFrameworkCore.SqlServer 9.0.2 from https://api.nuget.org/v3/index.json to C:\packages\microsoft.entityframe
workcore.sqlserver\9.0.2 with content hash PN65soRvSajLqr1kVRvpUwqI/rmab4x/6TxcYzyUVvg52DMPxx4Y760EZ6OzFhJnilP/WFEEzdftHsTsHQ64IQ==.
info :   GET https://api.nuget.org/v3/vulnerabilities/index.json
info :   OK https://api.nuget.org/v3/vulnerabilities/index.json 247ms
info :   GET https://api.nuget.org/v3-vulnerabilities/2025.02.27.05.27.11/vulnerability.base.json
info :   GET https://api.nuget.org/v3-vulnerabilities/2025.02.27.05.27.11/2025.02.28.05.27.13/vulnerability.update.json
info :   OK https://api.nuget.org/v3-vulnerabilities/2025.02.27.05.27.11/vulnerability.base.json 248ms
info :   OK https://api.nuget.org/v3-vulnerabilities/2025.02.27.05.27.11/2025.02.28.05.27.13/vulnerability.update.json 385ms
error: NU1202: Package Microsoft.EntityFrameworkCore.SqlServer 9.0.2 is not compatible with net48 (.NETFramework,Version=v4.8). Package Micr
osoft.EntityFrameworkCore.SqlServer 9.0.2 supports: net8.0 (.NETCoreApp,Version=v8.0)
error: Package 'Microsoft.EntityFrameworkCore.sqlServer' is incompatible with 'all' frameworks in project 'C:\Users\rbb\source\repos\Relaven
tLegalMatters\RelaventLegalMatters.csproj'.

**Comment by rawhide81** [comment]
Is it the fact that I'm using DatNet version 9? instead of 8?
