### ISSUE TITLE
XAML / BAML example

### ISSUE THREAD

**Issue by mc0re** [obfuscar/example#10]
Do I understand it right that Obfuscar does not process / rename BAML? It does notice, that a type is used by BAML, and keeps its name, but not any properties or methods. What should the <Skip...> set be for a class (control, converter, model) used in XAML?

**Comment by lextm** [comment]
Obfuscar tries its best to identify some types used by XAML/BAML, and skip them automatically,

https://github.com/obfuscar/obfuscar/blob/2.2.26/Obfuscar/Obfuscator.cs#L570

However, there are tons of other types it does not skip at this moment (converters for example), and no plan to spend more resources in that area.
