### ISSUE TITLE
How to run the example on macOS?

### ISSUE THREAD

**Issue by lextm** [obfuscar/example#4]
This example was developed on Windows, so compiling the solution on macOS will fail with errors.

**Comment by lextm** [comment]
Open obfuscar.xml and change its content to,
```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value="./Obfuscator_Output" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="KeyFile" value="./test.snk" />

  <Module file="$(InPath)/BasicExampleExe.exe" />
  <Module file="$(InPath)/BasicExampleLibrary.dll" />
</Obfuscator>
```
The obfuscation should work.

**Comment by ambertape** [comment]
Always getting this error when build...
For sample project and for one's own.
MacOS Catalina
![image](https://user-images.githubusercontent.com/68152775/97665495-97d51580-1a8c-11eb-92eb-839188cb92d2.png)
