### ISSUE TITLE
Error: "Unable to resolve dependency: System.Windows.Forms"

### ISSUE THREAD

**Issue by pablocar80** [obfuscar/example#6]
I tried to obfuscate my startup project, which is a NET Framework 4.7.2 and uses WinForms. I always get this error, even when I obfuscate the file directly from its bin folder (which includes all the dependencies):

`Unable to resolve dependency: System.Windows.Forms
`

**Comment by lextm** [comment]
You might try to add a folder like `C:\Windows\Microsoft.NET\Framework64\v4.0.30319` as assembly search folder, http://docs.obfuscar.com/getting-started/configuration.html#assembly-search-path-2-2-5
