### ISSUE TITLE
Package  Obfuscar.GlobalTool 2.2.19 has a package type DotnetTool ，that is not support by project "ARchGLCloud.Core"

### ISSUE THREAD

**Issue by liugt34** [obfuscar/example#7]
open nuget,and search "Obfuscar.GlobalTool",add install ,and then throw this error
![image](https://user-images.githubusercontent.com/8056013/59650883-3e7f8580-91ba-11e9-92ea-091d97215be6.png)

i dont know how to resolve it ?any body help？

**Comment by liugt34** [comment]
i worked it by this way 
`<ItemGroup>
    <PackageReference Include="Obfuscar" Version="2.2.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>`

**Comment by lextm** [comment]
`Obfuscar.GlobalTool` is a .NET Core global tool https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

Like you discovered, all users should use the package `Obfuscar` if their goals are different. The sample projects showed in this repo all use `Obfuscar` package reference.
