### ISSUE TITLE
Visual Studio for Mac Problem

### ISSUE THREAD

**Issue by 21piksel** [obfuscar/example#9]
Renaming:  fields...Parameters...Properties...Events...Methods...Types...Done.
An error occurred during processing:
**Key containers are not supported for Mono.**

On Visual Studio for Mac. Mono and Visual Studio up to date.

**Comment by lextm** [comment]
Signing with .pfx files is a Windows only feature. So it triggers such errors when trying to sign assemblies this way on Mac.

You have to switch to a .snk file to sign the assemblies, or simply don't sign any assemblies.
